apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: SOME_SECRET_VARIABLE
          value: UUUUU_SECRET
        - key: secret-key-space
          valueMap:
            SOME_SECRET_VARIABLE: UUUUU_SECRET
